name: docker
on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
permissions:
  contents: read
  packages: write
jobs:
  image:
    uses: hyperhash-org/.github/.github/workflows/docker-build.yml@main
    with:
      image-name: core
